name: Docs - (manual)

on:
  workflow_dispatch:
    branches: [ sphinx ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Requirements
        run: |
          pip3 install autodocsumm==0.2.0
          pip3 install docutils==0.18
          pip3 install sphinx==5.3.0
          pip3 install sphinx-rtd-theme==1.0.0
          pip3 install sphinx-sitemap
          pip3 install sphinxcontrib-spelling
          pip3 install sphinx-toolbox==3.4.0
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build docs
        run: |
          make github
          echo 'dcc-ex.com' > docs/_build/html/CNAME
          touch docs/_build/html/.nojekyll
      - name: Deploy
        if: github.ref == 'refs/heads/flash62au-restruct'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: docs/_build/html  # The folder the action should deploy.
