name: V5 Docs - (manual)

on:
  workflow_dispatch:
    branches: [ v5-release-docs ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Requirements
        # Allow sphinx-rtd-theme to choose the versions of sphinx & docutils
        run: |
          pip3 install -r requirements.txt
        # pip3 install sphinx-rtd-theme==1.2.0 \
            # sphinx-sitemap sphinxcontrib-spelling sphinx-toolbox ablog sphinx-design
      - name: Build docs
        run: |
          make github
          echo 'dcc-ex.com' > docs/_build/html/CNAME
          touch docs/_build/html/.nojekyll
      - name: Deploy
        if: github.ref == 'refs/heads/v5-release-docs'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: docs/_build/html  # The folder the action should deploy.
